
CREATE DATABASE `evoting`;

USE `evoting`;

grant all privileges on evoting.* to 'webapp'@'%';
flush privileges;

DROP TABLE IF EXISTS `candidates`;
create table `candidates` (
	`CandidateID` INT PRIMARY KEY,
	`FirstName` VARCHAR(50),
	`LastName` VARCHAR(50),
	`PoliticalParty` VARCHAR(11),
	`RunningMate` VARCHAR(50),
	`Platform` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

insert into `candidates`(`CandidateID`, `FirstName`, `LastName`, `PoliticalParty`, `RunningMate`, `Platform`) values
(1, 'Abbe', 'O'' Mara', 'Independent', 'Karley Haag', 'Phasellus sit amet erat.'),
(2, 'Loren', 'Henze', 'Democrat', 'Selah Sturm', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.'),
(3, 'Vania', 'Conway', 'Republican', 'Ansley Stone', 'Quisque id justo sit amet sapien dignissim vestibulum.'),
(4, 'Caritta', 'Le Teve', 'Republican', 'Colt Valenzuela', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.'),
(5, 'Jonathon', 'Dunley', 'Democrat', 'Jaquan Leblanc', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.'),
(6, 'Edvard', 'Alred', 'Democrat', 'Chyanne Batista', 'Nulla tellus. In sagittis dui vel nisl.'),
(7, 'Vere', 'Moxstead', 'Democrat', 'Kurt Grace', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.'),
(8, 'Corey', 'Blesli', 'Independent', 'Karley Haag', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.'),
(9, 'Tan', 'Studders', 'Democrat', 'Jodi Hoyt', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam.'),
(10, 'Nolana', 'Serjeantson', 'Democrat', 'Sawyer Rider', 'Duis aliquam convallis nunc.'),
(11, 'Tarrah', 'Caps', 'Republican', 'Kyron McCartney', 'Cras in purus eu magna vulputate luctus.'),
(12, 'Flory', 'Iley', 'Independent', 'Shlomo Buffington', 'Maecenas pulvinar lobortis est.'),
(13, 'Towny', 'Purvey', 'Democrat', 'Selah Sturm', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.'),
(14, 'Sayre', 'Avrasin', 'Independent', 'Jon Weir', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.'),
(15, 'Broddie', 'Samart', 'Independent', 'Sawyer Rider', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.'),
(16, 'Steven', 'Pardoe', 'Democrat', 'Dyllan Goodwin', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.'),
(17, 'Madeleine', 'Tretwell', 'Republican', 'Selah Sturm', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.'),
(18, 'Teresita', 'Pawlicki', 'Democrat', 'Colt Valenzuela', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.'),
(19, 'Lela', 'Birrel', 'Independent', 'Joslyn Richter', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.'),
(20, 'Paolo', 'Caroll', 'Independent', 'Hanna Kirkland', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.');

DROP TABLE IF EXISTS `votes`;
create table `votes` (
	`VoterID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`VoterName` VARCHAR(50),
	`SSN` VARCHAR(50),
	`Email` VARCHAR(50),
	`CandidateVote` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

insert into `votes`(`VoterName`, `SSN`, `Email`, `CandidateVote`) values
('Hildy Borris', '678-49-9725', 'gcastillou0@businessinsider.com', 'Ginelle Castillou'),
('Paul Sherlock', '868-67-7302', 'cdodd1@delicious.com', 'Conn Dodd'),
('Barbara Stockoe', '497-40-7487', 'rbakewell2@linkedin.com', 'Ronnica Bakewell'),
('Catharina McIlvaney', '576-27-6444', 'dgreenhead3@tuttocitta.it', 'Dalli Greenhead'),
('Karrie Kier', '656-79-8386', 'mmully4@bloglines.com', 'Morse Mully'),
('Howie Marquand', '487-23-0059', 'pnollet5@imageshack.us', 'Packston Nollet'),
('Tammy Stonestreet', '686-03-7032', 'ksill6@china.com.cn', 'Kip Sill'),
('Edsel Bispham', '618-44-8511', 'mkinsman7@tinypic.com', 'Meredeth Kinsman'),
('Demetrius Secker', '758-52-9556', 'sshirtliff8@zimbio.com', 'Shani Shirtliff'),
('Maximilianus Casterot', '185-60-4291', 'ibonnett9@youtu.be', 'Ingemar Bonnett'),
('Dacy Velden', '704-75-1712', 'cguerina@biblegateway.com', 'Charity Guerin'),
('Hernando Burghill', '298-40-9788', 'cpickoverb@macromedia.com', 'Cherie Pickover'),
('Theodor McInteer', '380-97-3866', 'ekeemsc@ehow.com', 'Eleni Keems'),
('Channa Woehler', '269-79-7420', 'tvasilyevskid@seesaa.net', 'Towney Vasilyevski'),
('Inglis Bazeley', '879-52-2260', 'rbragge@cloudflare.com', 'Romonda Bragg'),
('Gabbie Loosemore', '264-03-3963', 'mlaf@webmd.com', 'Miles La Wille'),
('Merwin Notley', '694-09-8378', 'espuffardg@army.mil', 'Ethan Spuffard'),
('Donall Imison', '746-58-0060', 'ecaberash@narod.ru', 'Erminia Caberas'),
('Irita Molohan', '532-47-4784', 'aoriordani@jalbum.net', 'Anson O''Riordan'),
('Valentia Gladtbach', '483-96-0804', 'dpaleyj@opera.com', 'Davidson Paley'),
('Garek Mullaly', '238-41-2618', 'mbleezek@sourceforge.net', 'Matthias Bleeze'),
('Conrade Louis', '527-65-8963', 'ehoultonl@wix.com', 'Elston Houlton'),
('Arluene Vivyan', '584-57-2834', 'jspikingsm@bigcartel.com', 'Jacqui Spikings'),
('Willette Guiton', '283-33-6373', 'ccoverdilln@webeden.co.uk', 'Catharine Coverdill'),
('Win Idale', '539-61-2249', 'jgosdino@privacy.gov.au', 'Jonie Gosdin'),
('Lynde Brik', '277-67-1135', 'tliesp@bandcamp.com', 'Tadeo Lies'),
('Edan Piddletown', '541-54-1313', 'sbartaliq@cam.ac.uk', 'Simone Bartali'),
('Fanchette Boorman', '630-95-2317', 'lmettsr@accuweather.com', 'Liane Metts'),
('Madelin Miliffe', '543-53-1363', 'rhounsoms@dmoz.org', 'Reginauld Hounsom'),
('Liam Hinze', '451-45-4936', 'afeltent@amazon.co.jp', 'Atalanta Felten'),
('Alexina Herety', '287-86-9456', 'qdunseithu@eepurl.com', 'Quintilla Dunseith'),
('Niels Tolossi', '506-99-2348', 'vwillockv@google.fr', 'Verina Willock'),
('Darren Causon', '717-17-9835', 'wdandw@techcrunch.com', 'Wyn Dand'),
('Galvan Steadman', '612-97-7200', 'tlarnex@homestead.com', 'Tera Larne'),
('Amos Davey', '804-83-1579', 'pburkinshawy@toplist.cz', 'Pearce Burkinshaw'),
('Roseann Martignon', '447-44-0731', 'mheynelz@wp.com', 'Missy Heynel'),
('Ricca Golborn', '835-19-0253', 'tcuthbert10@meetup.com', 'Ted Cuthbert'),
('Elwira Smurthwaite', '274-73-1487', 'ulynam11@unesco.org', 'Ursula Lynam'),
('Wylie Vido', '834-67-7123', 'brisley12@sohu.com', 'Bastien Risley'),
('Anett Routledge', '716-11-7653', 'sbeernaert13@wunderground.com', 'Susanetta Beernaert'),
('Lola Fearn', '750-52-7662', 'wrillstone14@joomla.org', 'Web Rillstone'),
('Beatrice Gavini', '575-21-5266', 'gkearns15@sun.com', 'Gillian Kearns'),
('Alva Brockley', '182-49-4671', 'nszepe16@imageshack.us', 'Nick Szepe'),
('Edgardo Sodory', '318-58-8350', 'dszantho17@g.co', 'Dare Szantho'),
('Ellen Connerry', '611-12-9411', 'bgullifant18@dion.ne.jp', 'Brian Gullifant'),
('Stanwood Scarborough', '347-58-6946', 'hclaxton19@is.gd', 'Harlene Claxton'),
('Ambros Lorentzen', '803-98-4583', 'mricharz1a@dailymail.co.uk', 'Margy Richarz'),
('Percival Dinesen', '627-92-8513', 'ladkins1b@gizmodo.com', 'Lanna Adkins'),
('Clarence Westell', '107-94-6104', 'lioselev1c@dailymail.co.uk', 'Lynda Ioselev'),
('Linnell Lehrian', '284-51-0990', 'gbignall1d@odnoklassniki.ru', 'Gratiana Bignall'),
('Essa Ewols', '881-46-6250', 'gmixter1e@disqus.com', 'Geraldine Mixter'),
('Mikaela Shuxsmith', '241-14-1029', 'tbooij1f@rambler.ru', 'Tiebold Booij'),
('Leonora Delmonti', '327-92-7241', 'nmcnair1g@accuweather.com', 'Norris McNair'),
('Catha Furney', '378-24-5092', 'lbartol1h@google.com.hk', 'Luigi Bartol'),
('Myrna Elegood', '490-94-7233', 'tklaggeman1i@jimdo.com', 'Tyler Klaggeman'),
('Etan Landis', '690-46-7712', 'fbush1j@epa.gov', 'Filberto Bush'),
('Benoite Yarnall', '384-31-8930', 'lfrantzeni1k@webeden.co.uk', 'Luise Frantzeni'),
('Ulla Ghest', '811-85-5129', 'hfillery1l@sciencedirect.com', 'Hunter Fillery'),
('Liz Tolomei', '180-92-8669', 'hfyldes1m@china.com.cn', 'Hodge Fyldes'),
('Tomlin Templar', '411-75-4305', 'cmathiassen1n@europa.eu', 'Cecil Mathiassen'),
('Rowena Naden', '311-30-4603', 'dhugnot1o@netscape.com', 'Darrell Hugnot'),
('Arlin Pietzker', '218-75-4687', 'ldoeg1p@webmd.com', 'Luisa Doeg'),
('Helge Baroch', '169-12-0436', 'fwebby1q@live.com', 'Filmore Webby'),
('Loutitia Dobbing', '654-61-5100', 'sforte1r@hud.gov', 'Shel Forte'),
('Hollis Oda', '553-93-5019', 'brase1s@buzzfeed.com', 'Brandice Rase'),
('Penn Hue', '434-32-5684', 'hstafford1t@arizona.edu', 'Herve Stafford'),
('Clary Kelbie', '241-09-8017', 'smarsie1u@aboutads.info', 'Sean Marsie'),
('Valencia Copnell', '734-94-2483', 'mstollberg1v@linkedin.com', 'Merv Stollberg'),
('Mathew Piquard', '794-67-1093', 'orapelli1w@acquirethisname.com', 'Osborn Rapelli'),
('Randie Guillem', '896-85-7560', 'mzottoli1x@latimes.com', 'Malinde Zottoli'),
('Octavius Twelve', '499-08-9034', 'lrough1y@who.int', 'Laurence Rough'),
('Sterling Dobbinson', '875-42-1123', 'rgamett1z@nydailynews.com', 'Renault Gamett'),
('Fitz Gueny', '754-37-9090', 'kberston20@hubpages.com', 'Kiel Berston'),
('Pete Gatsby', '526-83-9324', 'hlisett21@miitbeian.gov.cn', 'Howie Lisett'),
('Gerardo Whiten', '786-50-4311', 'tmaclucais22@redcross.org', 'Toni MacLucais'),
('Bobine Lodovichi', '244-08-5238', 'skhomich23@ca.gov', 'Sebastian Khomich'),
('Mireielle Swinnerton', '378-55-5311', 'rborrett24@imdb.com', 'Rosie Borrett'),
('Pyotr Inns', '623-22-2638', 'edupey25@amazon.com', 'Eduardo Dupey'),
('Karim Eaken', '703-81-3332', 'jlengthorn26@a8.net', 'Jesse Lengthorn'),
('Frederico Bowerbank', '690-68-1757', 'fcoughan27@imageshack.us', 'Frederich Coughan'),
('Flemming Leeds', '546-41-6634', 'carnull28@constantcontact.com', 'Camala Arnull'),
('Whit Vedikhov', '444-45-9587', 'ccammidge29@virginia.edu', 'Cort Cammidge'),
('Janenna Corneljes', '324-87-5003', 'kgimblet2a@nba.com', 'Kalindi Gimblet'),
('Allin Pedlingham', '600-71-6948', 'bbenian2b@nyu.edu', 'Brewster Benian'),
('Kurt Crossdale', '287-91-7589', 'bshakesbye2c@ucoz.ru', 'Bogey Shakesbye'),
('Licha Nelissen', '403-91-2907', 'mkingwell2d@amazonaws.com', 'Mohandas Kingwell'),
('Madelena Petrichat', '642-55-3044', 'dkyteley2e@hibu.com', 'Diego Kyteley'),
('Bobbee Winslow', '429-66-3419', 'lstower2f@prlog.org', 'Lauren Stower'),
('Freemon MacGrath', '325-77-8781', 'bdoneld2g@shinystat.com', 'Benedikta Doneld'),
('Fanni Demangel', '205-25-8703', 'fwhoolehan2h@godaddy.com', 'Frederich Whoolehan'),
('Patin Mulcaster', '896-52-1684', 'kstreetley2i@weibo.com', 'Keslie Streetley'),
('Candice Stener', '742-54-4740', 'lvanacci2j@mlb.com', 'Laurie Vanacci'),
('Boonie Robison', '383-56-8713', 'mtrayton2k@exblog.jp', 'Maximilien Trayton'),
('Marinna Tow', '684-10-0589', 'rsimonian2l@springer.com', 'Rubina Simonian'),
('Ezra Gierok', '491-18-4611', 'rbradd2m@shop-pro.jp', 'Ramon Bradd'),
('Mechelle Beverstock', '244-52-6514', 'emarquet2n@yahoo.com', 'Evelyn Marquet'),
('Reagen Richings', '294-22-4800', 'hmcgillivray2o@ox.ac.uk', 'Harris McGillivray'),
('Billi Bonafacino', '338-91-2069', 'mkleinzweig2p@businesswire.com', 'Moises Kleinzweig'),
('Virgilio Engall', '863-30-6245', 'mhoward2q@bloomberg.com', 'Merry Howard'),
('Teddy Ram', '282-84-1849', 'erosenshine2r@uol.com.br', 'Ernesto Rosenshine');

DROP TABLE IF EXISTS `complaints`;
create table `complaints` (
    `ComplaintID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`AuditorName` VARCHAR(50),
	`Candidate` VARCHAR(50),
	`VoterName` VARCHAR(50),
	`Complaint` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

insert into `complaints`(`AuditorName`, `Candidate`, `VoterName`, `Complaint`) values
('Camille Boland', 'Caitlynn Olivo', 'Elle Gillon', 'Nullam porttitor lacus at turpis.'),
('Efren Bradley', 'Edward StClair', 'Derek Glusby', 'Morbi porttitor lorem id ligula.'),
('Gage Fulmer', 'Kaden Lowery', 'Elsworth Cready', 'Aliquam non mauris.'),
('Efren Bradley', 'Gerardo Rees', 'Jobi Londer', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'),
('Kaiya Fitzsimmons', 'Kenyon Looney', 'Brien Antos', 'Vestibulum ac est lacinia nisi venenatis tristique.'),
('Camille Boland', 'Wesley Wyatt', 'Dru Maguire', 'Morbi quis tortor id nulla ultrices aliquet.'),
('Myles Milam', 'Lucille Baron', 'Chicky Warrack', 'Nulla tempus.'),
('Eric Coyne', 'Ciara Holm', 'L,urette Focke', 'Curabitur in libero ut massa volutpat convallis.'),
('Maribel Knoll', 'Gerardo Rees', 'Kyle Blundin', 'In quis justo.'),
('Raphael Oakes', 'Lucille Baron', 'Vivienne Bruck', 'Curabitur convallis.'),
('Gage Fulmer', 'Nayely Flores', 'Marga Scrooby', 'Duis ac nibh.'),
('Stacie Olivo', 'Raymundo Hurt', 'Willi Aylesbury', 'Curabitur convallis.'),
('Abigale Harter', 'Ross Tovar', 'Stanislaw Sumpner', 'Nullam sit amet turpis elementum ligula vehicula consequat.'),
('Stacie Olivo', 'Jarrett Pfeifer', 'Larissa Mathivat', 'Etiam vel augue.'),
('Aniyah Bentley', 'Davon Muhammad', 'Theressa Harrowing', 'Nam dui.'),
('Abigale Harter', 'Isabel Paige', 'Tiebout Hampshire', 'Morbi vel lectus in quam fringilla rhoncus.'),
('Houston Roush', 'Abraham Bagley', 'Cherie Chicco', 'Nulla justo.'),
('Houston Roush', 'Devyn Garvin', 'Dulcie Woodhams', 'Pellentesque at nulla.'),
('Aniyah Bentley', 'Mya Sheets', 'Rod Mosten', 'Curabitur convallis.'),
('Myles Milam', 'Jarrett Pfeifer', 'Ethelind Lemin', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.'),
('Myranda Hughes', 'Javonte Jennings', 'Ermentrude Emby', 'Ut at dolor quis odio consequat varius.'),
('Eliza Carlson', 'Ciara Holm', 'Kayley Beyn', 'Nulla nisl.'),
('Myranda Hughes', 'Jerome Girard', 'Emmalynn Avieson', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'),
('Eric Coyne', 'Larissa Paul', 'Rufus Chatto', 'Nunc rhoncus dui vel sem.'),
('Savanna Dyson', 'Ciara Holm', 'Rose Ventham', 'Morbi vel lectus in quam fringilla rhoncus.'),
('Sadie Lambert', 'Jarrett Pfeifer', 'Simona Zmitruk', 'Sed accumsan felis.'),
('Scott Pinto', 'Javonte Jennings', 'Vicky Byfford', 'Mauris sit amet eros.'),
('Savannah Breen', 'Desirae Mock', 'Bellina Waith', 'Morbi porttitor lorem id ligula.'),
('Eric Coyne', 'Jeniffer Wiley', 'Robenia Barkway', 'Nulla mollis molestie lorem.'),
('Savanna Dyson', 'Edward StClair', 'Addia Birden', 'Nulla tempus.'),
('Stacie Olivo', 'Gerardo Rees', 'Patsy Swatheridge', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'),
('Stacie Olivo', 'Ciara Holm', 'Hewie McRamsey', 'Maecenas tincidunt lacus at velit.'),
('Abigale Harter', 'Larissa Paul', 'Antoine Tewnion', 'In congue.'),
('Stacie Olivo', 'Jeniffer Wiley', 'Milzie O''Mailey', 'Suspendisse potenti.'),
('Mustafa Herron', 'Juan Searcy', 'Aleksandr Vouls', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.'),
('Stacie Olivo', 'Nayely Flores', 'Ramsay Cantwell', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'),
('Savanna Dyson', 'Desirae Mock', 'Gasper Greggs', 'Fusce consequat.'),
('Camille Boland', 'Jerome Girard', 'Kaitlin Weedenburg', 'Praesent blandit lacinia erat.'),
('Myranda Hughes', 'Raymundo Hurt', 'Alexis Duggan', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'),
('Raymundo Eller', 'Edward StClair', 'Bevon Hughill', 'Vestibulum rutrum rutrum neque.'),
('Abigale Harter', 'Nayely Flores', 'Leo Simper', 'Donec posuere metus vitae ipsum.'),
('Sadie Lambert', 'Kenyon Looney', 'Warden Cogle', 'Integer a nibh.'),
('Mustafa Herron', 'Devyn Garvin', 'Karisa Jeannaud', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.'),
('Houston Roush', 'Larissa Paul', 'Martguerita Crossman', 'Nullam varius.'),
('Milan Spann', 'Rocky Marsh', 'Stanleigh Cullon', 'Phasellus sit amet erat.'),
('Jayden Troyer', 'Carina Wiggins', 'Gordy Ixer', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.'),
('Susan Ricketts', 'Abraham Bagley', 'Oby Ferronet', 'Maecenas rhoncus aliquam lacus.'),
('Tate Boucher', 'Larissa Paul', 'Susi Macenzy', 'Morbi a ipsum.'),
('Raphael Oakes', 'Larissa Paul', 'Lira Planks', 'Vestibulum rutrum rutrum neque.'),
('Houston Roush', 'Jarrett Pfeifer', 'Shir Chainey', 'In eleifend quam a odio.'),
('Aniyah Bentley', 'Noel Faust', 'Thornie Graalmans', 'Fusce posuere felis sed lacus.'),
('Brenna Sabo', 'Wesley Wyatt', 'Cassy Pordal', 'Fusce consequat.'),
('Craig Cloud', 'Jerome Girard', 'Verena Shaddock', 'Morbi porttitor lorem id ligula.'),
('Savanna Dyson', 'Nayely Flores', 'Loydie Wastie', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.'),
('Eliza Carlson', 'Vladimir Pagan', 'Ashby Wiper', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.'),
('Houston Roush', 'Jarrett Pfeifer', 'Sharyl Dockery', 'Aliquam sit amet diam in magna bibendum imperdiet.'),
('Craig Cloud', 'Jacquez Vitale', 'Karel Janczak', 'Nulla tellus.'),
('Gage Fulmer', 'Noel Faust', 'Eldon Achrameev', 'Suspendisse ornare consequat lectus.'),
('Savanna Dyson', 'Devyn Garvin', 'Beverly Sieghart', 'Morbi porttitor lorem id ligula.'),
('Brenna Sabo', 'Raymundo Hurt', 'Leonie Lowrey', 'Duis ac nibh.'),
('Jarrod Werner', 'Nayely Flores', 'Gaile Denerley', 'Suspendisse potenti.'),
('Brenna Sabo', 'Caitlynn Olivo', 'Mala Ochiltree', 'Vestibulum sed magna at nunc commodo placerat.'),
('Kaiya Fitzsimmons', 'Wesley Wyatt', 'Annmarie Beckett', 'Nulla suscipit ligula in lacus.'),
('Eric Coyne', 'Wesley Wyatt', 'Cordy Bleddon', 'Donec vitae nisi.'),
('Abigale Harter', 'Vladimir Pagan', 'Meggy Diprose', 'Mauris sit amet eros.'),
('Tate Boucher', 'Caitlynn Olivo', 'Felicle Barrs', 'Nunc rhoncus dui vel sem.'),
('Savannah Breen', 'Vladimir Pagan', 'Glenine Gland', 'Vestibulum rutrum rutrum neque.'),
('Raymundo Eller', 'Edward StClair', 'Sanders Pordall', 'Vivamus vel nulla eget eros elementum pellentesque.'),
('Gage Fulmer', 'Jacquez Vitale', 'Kip Bwy', 'Integer a nibh.'),
('Gage Fulmer', 'Jacquez Vitale', 'Jason Steuhlmeyer', 'Duis consequat dui nec nisi volutpat eleifend.'),
('Jarrod Werner', 'Larissa Paul', 'Siobhan Mallender', 'Nunc purus.'),
('Sadie Lambert', 'Abraham Bagley', 'Hasty Van Baaren', 'Cras pellentesque volutpat dui.'),
('Brenna Sabo', 'Vladimir Pagan', 'Gizela Wingar', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'),
('Alivia Holder', 'Gerardo Rees', 'Rivy McSkin', 'In hac habitasse platea dictumst.'),
('Eric Coyne', 'Jeniffer Wiley', 'Adelind Bartelet', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.'),
('Susan Ricketts', 'Raymundo Hurt', 'Veronique Canellas', 'Maecenas tincidunt lacus at velit.'),
('Scott Pinto', 'Mya Sheets', 'Eben McNysche', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.'),
('Jayden Troyer', 'Kaden Lowery', 'Payton Walwood', 'Aliquam non mauris.'),
('Eliza Carlson', 'Jamel Bach', 'Reinaldos Mixworthy', 'Donec vitae nisi.'),
('Karolina Starr', 'Carina Wiggins', 'Sherm Hulson', 'Vivamus vestibulum sagittis sapien.'),
('Craig Cloud', 'Noel Faust', 'Orson Surr', 'Fusce consequat.'),
('Craig Cloud', 'Lucille Baron', 'Israel Bygott', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam.'),
('Alivia Holder', 'Desirae Mock', 'Fawne Hostan', 'Integer non velit.'),
('Raphael Oakes', 'Jamel Bach', 'Michelle Rickards', 'Duis mattis egestas metus.'),
('Mustafa Herron', 'Javonte Jennings', 'Normy Goede', 'Duis at velit eu est congue elementum.'),
('Susan Ricketts', 'Davon Muhammad', 'Garland O''Teague', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.'),
('Savanna Dyson', 'Raymundo Hurt', 'Whitney Mabbot', 'Proin at turpis a pede posuere nonummy.'),
('Seth Akins', 'Mya Sheets', 'Ethe Yu', 'Integer non velit.'),
('Jarrod Werner', 'Carina Wiggins', 'Worth Parkman', 'In congue.'),
('Brenna Sabo', 'Raymundo Hurt', 'Agna Diben', 'Nulla ut erat id mauris vulputate elementum.'),
('Maribel Knoll', 'Jeniffer Wiley', 'Arthur Harmar', 'Phasellus id sapien in sapien iaculis congue.'),
('Camille Boland', 'Nayely Flores', 'Sophie Elphinston', 'Vivamus tortor.'),
('Efren Bradley', 'Jamel Bach', 'Micheil Corkish', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.'),
('Karolina Starr', 'Kaden Lowery', 'Ally Orable', 'In hac habitasse platea dictumst.'),
('Craig Cloud', 'Gerardo Rees', 'Waly Ronchetti', 'Phasellus in felis.'),
('Savanna Dyson', 'Abraham Bagley', 'Cirstoforo Yuryatin', 'Sed vel enim sit amet nunc viverra dapibus.'),
('Seth Akins', 'Ross Tovar', 'Eward Newcomb', 'In hac habitasse platea dictumst.'),
('Mustafa Herron', 'Noel Faust', 'Martelle Cowoppe', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.'),
('Tate Boucher', 'Abraham Bagley', 'Orv Crehan', 'Nunc nisl.');

DROP TABLE IF EXISTS `bans`;
create table `bans` (
	`BanID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`AdminName` VARCHAR(50),
	`BannedSSN` VARCHAR(50),
	`Reason` VARCHAR(23),
	`Length` VARCHAR(9),
	`Details` TEXT
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

insert into `bans`(`AdminName`, `BannedSSN`, `Reason`, `Length`, `Details`) values
('Jorey Grelik', '478-32-6503', 'Hacking System', 'Permanent', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.'),
('Weidar Calderhead', '382-16-8440', 'Hacking System', '10 Years', 'Aliquam erat volutpat.'),
('Mack Saunder', '530-08-4559', 'Abuse', 'Permanent', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.'),
('Amalia Coughan', '136-24-7203', 'Abuse', 'Permanent', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.'),
('Thekla Keemar', '558-37-2798', 'Abuse', '10 Years', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.'),
('Averyl Giraldo', '522-76-2735', 'Abuse', '10 Years', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.'),
('Nicolina Ainsbury', '410-66-2085', 'Abuse', '5 Years', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'),
('Carolin Normanville', '319-81-6809', 'Crimes Against Humanity', '10 Years', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.'),
('Becka Belk', '831-86-5544', 'Crimes Against Humanity', '50 Years', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.'),
('Ruth Wearn', '586-50-3513', 'Hacking System', '50 Years', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.'),
('Leo Cicutto', '438-34-1929', 'Hacking System', 'Permanent', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.'),
('Reinhold Basford', '569-79-9609', 'Abuse', '5 Years', 'Integer ac leo. Pellentesque ultrices mattis odio.'),
('Inez Drewett', '898-98-5625', 'Crimes Against Humanity', 'Permanent', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.'),
('Yale Maffetti', '571-72-4558', 'Abuse', '50 Years', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.'),
('Alaine Ewan', '779-50-3243', 'Hacking System', '10 Years', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.'),
('Kinny Puttick', '770-47-4078', 'Abuse', '10 Years', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.'),
('Loraine Whimper', '513-69-6472', 'Abuse', '5 Years', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.'),
('Ninette Aharoni', '505-91-2452', 'Crimes Against Humanity', 'Permanent', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.'),
('Jerald Triplow', '639-81-0162', 'Crimes Against Humanity', '5 Years', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.'),
('Maribelle Offield', '385-56-8020', 'Crimes Against Humanity', '5 Years', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.'),
('Marcie Pigott', '371-88-9924', 'Crimes Against Humanity', '50 Years', 'Nulla suscipit ligula in lacus.'),
('Jemmie Van Hesteren', '748-47-5847', 'Hacking System', '5 Years', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.'),
('Desmund Lochran', '212-46-5837', 'Hacking System', 'Permanent', 'Donec posuere metus vitae ipsum. Aliquam non mauris.'),
('Coriss Holt', '881-99-2463', 'Abuse', '50 Years', 'In congue. Etiam justo. Etiam pretium iaculis justo.'),
('Dix Rosenfelt', '435-15-1497', 'Abuse', '5 Years', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.'),
('Heda De Bruijne', '654-59-4252', 'Voter Fraud', '5 Years', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.'),
('Blakelee Foad', '863-13-5120', 'Hacking System', '50 Years', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.'),
('Adrianne Labba', '495-50-0822', 'Abuse', '5 Years', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.'),
('Billy Baume', '235-90-2683', 'Hacking System', '5 Years', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'),
('Simeon Ratcliffe', '470-64-1527', 'Crimes Against Humanity', '50 Years', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.'),
('Kimbra Matussov', '333-78-0442', 'Abuse', '10 Years', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.'),
('Kris Harford', '340-26-4481', 'Crimes Against Humanity', '50 Years', 'Nam tristique tortor eu pede.'),
('Thornton Whitford', '271-27-3425', 'Crimes Against Humanity', '50 Years', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.'),
('Pammie Tonkin', '468-98-0087', 'Crimes Against Humanity', '10 Years', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.'),
('Torie Ruttgers', '499-89-7510', 'Crimes Against Humanity', '5 Years', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.'),
('Gardy Upson', '136-74-3874', 'Hacking System', '5 Years', 'Phasellus sit amet erat.'),
('Garnet Pettiford', '841-56-3829', 'Crimes Against Humanity', '50 Years', 'Etiam faucibus cursus urna. Ut tellus.'),
('Victoria Connerly', '698-08-1690', 'Voter Fraud', '5 Years', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.'),
('Sherwynd Price', '308-60-9729', 'Hacking System', '10 Years', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.'),
('Dane Simic', '638-90-2748', 'Voter Fraud', '5 Years', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.'),
('Garek Medgewick', '674-90-9753', 'Voter Fraud', '10 Years', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.'),
('Trixie Bourdis', '615-39-3741', 'Crimes Against Humanity', 'Permanent', 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.'),
('Tomasina Andrichak', '560-33-4072', 'Crimes Against Humanity', 'Permanent', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.'),
('Mycah MacUchadair', '677-59-7143', 'Voter Fraud', '50 Years', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.'),
('Titus Colledge', '810-43-1116', 'Voter Fraud', '10 Years', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.'),
('Karine Tutchener', '642-89-3628', 'Crimes Against Humanity', '10 Years', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.'),
('Mace Synke', '333-46-8382', 'Abuse', '5 Years', 'Nulla nisl. Nunc nisl.'),
('Nikolos Rowlatt', '620-83-4858', 'Voter Fraud', '5 Years', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.'),
('Maighdiln Hovenden', '804-99-4162', 'Voter Fraud', '10 Years', 'Sed ante. Vivamus tortor.'),
('Daffi Hallahan', '448-08-0453', 'Crimes Against Humanity', '5 Years', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.'),
('Elinore Acarson', '573-67-6057', 'Voter Fraud', '50 Years', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.'),
('Kerrin Frossell', '578-25-4540', 'Abuse', '10 Years', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.'),
('Aaren Corfield', '553-67-6170', 'Voter Fraud', '10 Years', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.'),
('Vern Stellino', '188-48-7870', 'Voter Fraud', '10 Years', 'Suspendisse potenti.'),
('Clarke Aslen', '344-50-7594', 'Voter Fraud', 'Permanent', 'Etiam faucibus cursus urna. Ut tellus.'),
('Jacquenetta Hannon', '842-16-1784', 'Voter Fraud', '10 Years', 'Phasellus id sapien in sapien iaculis congue.'),
('Marlo Gallandre', '201-71-6137', 'Voter Fraud', 'Permanent', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.'),
('Roxanne Abba', '536-27-3541', 'Abuse', '10 Years', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.'),
('Hammad Westerman', '873-83-9085', 'Abuse', '50 Years', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.'),
('Dael Bilham', '113-37-0781', 'Voter Fraud', 'Permanent', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.'),
('Laurens Chatan', '187-65-4151', 'Abuse', '10 Years', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.'),
('Yolande Macauley', '788-92-5403', 'Hacking System', '50 Years', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.'),
('Vittorio Gantley', '620-56-2934', 'Hacking System', '10 Years', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam. Suspendisse potenti.'),
('Ferdinande Saynor', '477-29-4610', 'Voter Fraud', '50 Years', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.'),
('Felizio Fearon', '777-35-8644', 'Voter Fraud', '5 Years', 'Etiam faucibus cursus urna. Ut tellus.'),
('Inesita Durdan', '570-16-4686', 'Hacking System', 'Permanent', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.'),
('Yorke Truggian', '489-91-7587', 'Hacking System', '50 Years', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.'),
('Marne Duckinfield', '111-90-4518', 'Abuse', '50 Years', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.'),
('Lalo Worvell', '516-13-7350', 'Voter Fraud', '50 Years', 'In hac habitasse platea dictumst.'),
('Rex Huckel', '165-10-4879', 'Voter Fraud', '10 Years', 'Mauris sit amet eros.'),
('Rosetta Falvey', '753-90-6459', 'Crimes Against Humanity', '5 Years', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.'),
('Templeton Harrop', '408-10-2146', 'Voter Fraud', '5 Years', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.'),
('Felice Buckham', '458-60-2829', 'Hacking System', '5 Years', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'),
('Norbert Ortet', '489-18-6241', 'Voter Fraud', '5 Years', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Mauris viverra diam vitae quam.'),
('Dyna Aaronson', '779-84-3502', 'Hacking System', '5 Years', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.'),
('Omero Schreurs', '598-02-9513', 'Crimes Against Humanity', 'Permanent', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.'),
('Hendrick Parsonage', '696-77-7174', 'Crimes Against Humanity', '10 Years', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.'),
('Cassey Grundy', '346-81-5319', 'Voter Fraud', 'Permanent', 'Vestibulum ac est lacinia nisi venenatis tristique.'),
('Shelden Ilyenko', '767-09-3932', 'Voter Fraud', '10 Years', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.'),
('Frazier Paaso', '676-79-6147', 'Voter Fraud', 'Permanent', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.'),
('Catriona Baggiani', '337-96-1529', 'Voter Fraud', 'Permanent', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.'),
('Brita McBride', '541-26-6507', 'Abuse', '50 Years', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.'),
('Ogdon Ivantsov', '749-16-0763', 'Hacking System', '5 Years', 'Vivamus vel nulla eget eros elementum pellentesque.'),
('Jelene Klement', '306-23-5777', 'Voter Fraud', '10 Years', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.'),
('Padriac Goldthorp', '332-40-1814', 'Hacking System', '5 Years', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.'),
('Vernen McNiff', '203-04-2807', 'Hacking System', '5 Years', 'Nullam molestie nibh in lectus.'),
('Avictor Wibberley', '747-06-1947', 'Crimes Against Humanity', 'Permanent', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.'),
('Dulci Elizabeth', '407-40-0103', 'Voter Fraud', '10 Years', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');